services:
  - type: web
    name: sap-perdidas-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: AUTH_TOKEN
        generateValue: true
    advanced:
      forceHttps: true
      autoDeploy: true