services:
  - type: web
    name: sap-perdidas-api
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    env: node
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production